apiVersion: v1
kind: Service
metadata:
  name: "mosquitto-broker"
spec:
  type: ClusterIP
  ports:
  - name: "broker-port"
    port: 1883
    targetPort: 1883
    protocol: TCP
  selector:
    service_broker: "mosquitto-broker"
    service_api_server: "broker-api-server"
---
apiVersion: v1
kind: Service
metadata:
  name: "broker-api-server"
spec:
  type: ClusterIP
  ports:
  - name: "api-port"
    port: 4444
    targetPort: 4444
    protocol: TCP
  selector:
    service_broker: "mosquitto-broker"
    service_api_server: "broker-api-server"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "mosquitto-broker"
spec:
  selector:
    matchLabels:
      service_broker: "mosquitto-broker"
      service_api_server: "broker-api-server"
  template:
    metadata:
      labels:
        service_broker: "mosquitto-broker"
        service_api_server: "broker-api-server"
    spec:
      containers:
      - name: mosquitto-broker-plugin
        image: mosquitto-broker:0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1883
          name: broker-port
          protocol: TCP    
      - name: mqtt-api-server
        image: broker-api-server:0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4444
          name: "api-port"
          protocol: TCP
      nodeSelector:
        kubernetes.io/hostname: "rishikesh"