apiVersion: apps/v1
kind: Deployment
metadata:
  name: "mqtt-client-subscriber"
spec:
  selector:
    matchLabels:
      app: "subscriber"
  template:
    metadata:
      labels:
        app: "subscriber"
    spec:
      containers:
      - name: subscriber-client
        image: mqtt-client:0.0.1
        imagePullPolicy: IfNotPresent
        env:
        - name: CLIENT_TYPE
          value: "SUBSCRIBER_CONSOLE"
        - name: MQTT_HOST
          value: "mosquitto-broker.default.svc.cluster.local"
        - name: MQTT_PORT
          value: "1883"
        - name: MQTT_USERNAME
          value: "xyz"
        - name: MQTT_PASSWORD
          value: "123"
        - name: MQTT_QOS
          value: "1"
        - name: SUBSCRIBER_TOPIC
          value: "test/#"   
      nodeSelector:
        kubernetes.io/hostname: "rishikesh"